### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by xrandox** [dlamkins/gw2pathing-wiki#8]
Bit of a To-do List:
## User Guide
- [ ] Troubleshooting/Common issues Page? idk if we need one or not

## Marker Pack Development
- [ ] Introduction isn't really an introduction
- [ ] Development Tools
- [ ] Tutorials
  - [ ] Fill this out with the other tuts and then see what else needs added
  - [ ] At least get a pack structure tut up since lua scripting refers to it

## Lua Scripting
- [ ] Work through all the TODO:'s I littered around
- [ ] IBehavior needs fleshed out
- [ ] Finish Tuts
  - [ ] Tick Handlers/OnTick Tutorial
  - [ ] Altering Behaviors
  - [ ] Handling Trails
